import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  build: {
    cssCodeSplit: true,
    cssMinify: false,
    sourcemap: true,
    lib: {
      entry: {
        index: "src/index.ts",
        button: "src/button.tsx",
        "annotated-action": "src/annotated-action.tsx",
        "text-button": "src/text-button.tsx",
        card: "src/card.tsx",
        dialog: "src/dialog.tsx",
        drawer: "src/drawer.tsx",
        layout: "src/layout.tsx",
        meter: "src/meter.tsx",
        menu: "src/menu.tsx",
        popover: "src/popover.tsx",
        polish: "src/polish.tsx",
        "react-node": "src/react-node.ts",
        accordion: "src/accordion.tsx",
        avatar: "src/avatar.tsx",
        separator: "src/separator.tsx",
        tabs: "src/tabs.tsx",
        select: "src/select.tsx",
        input: "src/input.tsx",
        textarea: "src/textarea.tsx",
        "form-field": "src/form-field.tsx",
        checkbox: "src/checkbox.tsx",
        radio: "src/radio.tsx",
        switch: "src/switch.tsx",
        tooltip: "src/tooltip.tsx",
        toast: "src/toast.tsx",
        notice: "src/notice.tsx",
        loading: "src/loading.tsx",
        "feedback-prompt": "src/feedback-prompt.tsx",
        "page-header": "src/page-header.tsx",
        "empty-state": "src/empty-state.tsx",
        "code-block": "src/code-block.tsx",
        styles: "src/styles.css",
        public: "src/public.css",
        reset: "src/reset.css",
      },
      formats: ["es"],
      fileName: (_format, entryName) => `${entryName}.js`,
    },
    rollupOptions: {
      external: ["react", "react-dom", "react/jsx-runtime", /^@base-ui\/react/],
    },
  },
  test: { environment: "jsdom", setupFiles: ["src/test-setup.ts"], exclude: process.env.BROWSER_TESTS ? ["**/node_modules/**", "**/dist/**"] : ["**/node_modules/**", "**/dist/**", "**/*.browser.test.ts"] },
});
